version: "3"
services:
  redis:
    image: redis:alpine
  varnish:
    image: varnish
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    tmpfs:
      - /var/lib/varnish:exec
    ports:
      - 8080:80
    depends_on:
      - app
  app:
    build: .
    environment:
      REDIS_URL: "redis://redis"
    depends_on:
      - redis
